### ISSUE TITLE
YARN build - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Jan-Pleva** [jfrog/build-info-go#163]
### Describe the bug

During the yarn build the error with memory appears.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc3332e]

### Current behavior

There should be any error.

### Reproduction steps

`Starting: JFrog YARN install
==============================================================================
Task         : JFrog CLI V2
Description  : Run your own JFrog CLI command.
Version      : 1.6.1
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/JFROG/JFrog+Azure+DevOps+Extension#JFrogAzureDevOpsExtension-ExecutingJFrogCLICommands)
==============================================================================
Found tool in cache: jf 2.37.1 x64
Running jfrog-cli from /opt/hostedtoolcache/jf/2.37.1/x64/jf
JFrog CLI version: 2.37.1
Executing JFrog CLI Command:
/opt/hostedtoolcache/jf/2.37.1/x64/jf c add "Marvin3.VBtOModule.Client.JFrog.Yaml_20230518.2_jfrog_cli_cmd_1684404202880" --url="[https://artifactory.skoda.vwgroup.com/"](https://artifactory.skoda.vwgroup.com/%22) --interactive=false --access-token-stdin
Executing JFrog CLI Command:
/opt/hostedtoolcache/jf/2.37.1/x64/jf c use "Marvin3.VBtOModule.Client.JFrog.Yaml_20230518.2_jfrog_cli_cmd_1684404202880"
12:03:22 [Info] Using server ID 'Marvin3.VBtOModule.Client.JFrog.Yaml_20230518.2_jfrog_cli_cmd_1684404202880' (https://artifactory.skoda.vwgroup.com/)
Executing JFrog CLI Command:
/opt/hostedtoolcache/jf/2.37.1/x64/jf yarn-config --repo-resolve=front-npm-virtual
12:03:22 [Info] yarn build config successfully created.
Executing JFrog CLI Command:
/opt/hostedtoolcache/jf/2.37.1/x64/jf yarn install --no-immutable --build-name=marvin-external-app --build-number=20230518.2
12:03:23 [Info] Running Yarn...
12:03:24 [Info] Preparing for dependencies information collection... For the first run of the build, the dependencies collection may take a few minutes. Subsequent runs should be faster.
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 80ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc3332e]

goroutine 1 [running]:
github.com/jfrog/build-info-go/build.(*YarnModule).appendDependencyRecursively(0xc0005240d8?, 0xc00033f410?, {0x1af2b70?, 0xc0005240d8?, 0xc00065ae70?}, 0x7fcf1c3b79b8?, 0xc00031d590?)
	/root/go/pkg/mod/github.com/jfrog/build-info-go@v1.9.3/build/yarn.go:97 +0x2e
github.com/jfrog/build-info-go/build.(*YarnModule).getDependenciesMap(0xc000335340)
	/root/go/pkg/mod/github.com/jfrog/build-info-go@v1.9.3/build/yarn.go:91 +0x93
github.com/jfrog/build-info-go/build.(*YarnModule).Build(0xc000335340)
	/root/go/pkg/mod/github.com/jfrog/build-info-go@v1.9.3/build/yarn.go:72 +0x85
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/yarn.(*YarnCommand).Run(0xc0003646e0)
	/root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.32.1/artifactory/commands/yarn/yarn.go:108 +0x365
github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0x125f8b0?, 0xc0003646e0})`

### Expected behavior

build the yarn.

### Operating system type and version

JFrog CLI version: 2.37.1

**Comment by Jan-Pleva** [comment]
Some info?
